### ISSUE TITLE
crafting works but fails to put crafted item in inventory 

### ISSUE THREAD

**Issue by Soldierofthelam** [Coffeelot/cw-crafting#1]
[ 805672] [b2699_GTAProce] CrBrowserMain/ successfully crafted an item (@cw-crafting/html/script.js:35)
[ 818766] [b2699_GTAProce] CrBrowserMain/ successfully crafted an item (@cw-crafting/html/script.js:35)
[ 823078] [b2699_GTAProce] CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@qb-target/html/js/app.js:50)

[  script:cw-crafting] 1
[  script:cw-crafting] SCRIPT ERROR: @cw-crafting/server/server.lua:31: attempt to perform arithmetic on a nil value (field 'amount')

SCRIPT ERROR: @cw-crafting/server/server.lua:33: attempt to index a nil value (global 'Item')

![Desktop Screenshot 2023 03 20 - 13 06 23 17](https://user-images.githubusercontent.com/117047687/226415290-67d6846b-4cd5-4c8d-b798-4fa7d4c7b84b.png)

![Untitled](https://user-images.githubusercontent.com/117047687/226244038-9160803f-dc74-4d61-8790-561e1540e3b4.png)

**Comment by Soldierofthelam** [comment]
Also when closing the crafting menu, tries to call for emote animation.

**_"this line of code isn't triggering to add player item to inventory"_**
Player.Functions.AddItem(item.name, item.amount*craftingAmount)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items[item.name], "add")
**_"this line of code may be related to the qbcore bug with items, but the the above line of code doe's not function"_**
https://github.com/qbcore-framework/qb-core/issues/961

**Comment by Coffeelot** [comment]
Patch out. Please verify it's fixed.

**Comment by Soldierofthelam** [comment]
> Patch out. Please verify it's fixed.

Yes very nice and thank you so much!
No error's
Working on latest QBcore version.
It's nice to see an actual clean looking and simple UI to use!
  I feel like an idiot now cause I changed the server file but completely forgot to change the client side till I seen your patch fix. 

![Desktop Screenshot 2023 03 21 - 14 08 35 48](https://user-images.githubusercontent.com/117047687/226702758-7a651d72-dd6e-4a42-8efd-f9c577104aa6.png)

**Comment by Coffeelot** [comment]
Thanks for all the error logs and code screenshot. They helped make this fast
👍
