### ISSUE TITLE
Problem when adding a table.

### ISSUE THREAD

**Issue by lungwang76** [Coffeelot/cw-crafting#3]
Hello, Sorry to disturb you but i have a little problem.
i have add a new table for crafting so i do something like that :

	kitchen = {
        title = "Preparation",
        objects = { 'prop_cooker_03' },
		jobType = { ['vanilla'] = 1 },
		locations = {  vector3(134.62, -1287.4, 29.27), },
		spawnTable = { { coords= vector4(134.64, -1287.3, 29.27, 35.84), prop = 'prop_cooker_03' } }
    },
    So you can see i have choose the props, add a spawn are, the job you can use it.
    i have made a recipe like that :
    
     ['dusche'] = { 
	name = 'dusche', 
	craftTime= 1000, 
	category = "Materials", 
	materials = {  
		rum = 1, 
		logger = 1, 
		mintleaf = 1,

	}, 
	jobs = { 
		{ type = 'vanilla', level = 1 } 
	 },
	requireBlueprintAndJob = false, 
	tables = {'kitchen'}
},
So i have put the samename of each item in my shared item, i have put the time to craft the category and the job restriction and at the bottom the tale needed.
Normaly if i start the server and the script is ensure, i see the props spawner, i can use the qb-target on it for selection him but when i arrived in the menu i just a have a window this just say " choose category" but none appears.
i have check  lot of time with change props, change category, change spawn area change job needed, i have try with my job vanilla and each grade nothing, i have try with mechanicjob and each grade nothing, so i am a bit lost.

**Comment by Coffeelot** [comment]
Does other tables work? Otherwise, a common problem that results in this is that you have items in the recipes that you don't have in your items.lua

**Comment by lungwang76** [comment]
Yes all others tables like weapon, mechanic and other work well, and i have check like maybe 6 times all items i use in the recipe, i have add them already in items.lua
that why i dont understand why that doesn't work properly

when i sue the qb target on the props, something open with write in " Workbench" and under that "Choose category"
but i have no choice after that

**Comment by Coffeelot** [comment]
I assume you're seeing no errors as you didn't mention it?

I don't remember fully, but I'm not sure there's an "amount" check (and default). Try adding it to your item also, since it's missing.
